version: "3"

services:
  portainer:
    build:
      context: portainer/
      args:
        - GOOS=${TARGETOS:-linux}
        - GOARCH=${TARGETARCH:-amd64}
        - GIT_TAG=${GIT_TAG:-2.0.0}
    container_name: ${PORT_CONTAINER_NAME:-portainer}
    restart: ${PORT_RESTART:-unless-stopped}
    volumes:
      - ${LOCAL_STACK_DIR}/portainer/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - portainer.env
    command: --admin-password="${PORT_ENCRYPTED_PWD}"

networks:
  default:
    external:
      name: ${NETWORK}
